-- ═══════════════════════════════════════════════════════════════════════
-- 2026-10-02_model_slug_inventory.sql
--
-- READ-ONLY. No INSERT, no UPDATE, no DDL. Nothing here changes anything.
-- Run in phpMyAdmin, one query at a time.
--
-- PURPOSE
-- Answer the three questions that decide step 2 of the model-URL work:
--
--   Q1  How many model pages are there really? The crawl showed 10 on the
--       homepage; /lookbook has 41 cards. If it is ~41, that is 41 new
--       indexable URLs and the content threshold matters much more.
--   Q2  Do any models have no brand? Those get a bare slug — it works, but
--       it is a data defect worth fixing at source before URLs exist.
--   Q3  Would any two models share a URL? A collision is a hard stop.
--
-- ─── IMPORTANT: THIS SQL DOES NOT PRODUCE THE CANONICAL SLUG ───────────
-- The authoritative slug comes from src/utils/modelSlug.js, and the
-- committed src/config/modelSlugs.json must be generated by
--
--     node scripts/dumpModelSlugs.js
--
-- not from this file. The difference is accents: the JS folds them to their
-- ASCII base ("Café" -> cafe) by normalising first, which MySQL's
-- REGEXP_REPLACE cannot do — it DROPS the character instead ("Café" -> caf).
-- For ASCII-only names, which is everything in the catalogue today, the two
-- agree. The slug column below is therefore for READING, and if any model
-- name carries an accent the two will disagree and the JS wins.
--
-- VANITY_CAT_ID = 1, matching src/middleware/megaMenuData.js:24.
-- ═══════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────
-- 0. Does your server have REGEXP_REPLACE?  (MySQL 8.0+ / MariaDB 10.0.5+)
--    If this errors, skip the slug column and use query 1b instead.
-- ───────────────────────────────────────────────────────────────────────
SELECT VERSION() AS server_version,
       REGEXP_REPLACE('Mid-Century Modern', '[^a-zA-Z0-9]+', '-') AS regexp_works;


-- ───────────────────────────────────────────────────────────────────────
-- Q1. THE FULL INVENTORY — every model page that would exist, with its URL
--     and how many products sit behind it.
--
--     `products` is the count that decides whether the page deserves to be
--     indexed at all. Read it against the 25-product threshold already in
--     use for the filtered collections (themeSettings seo.filter_landing_
--     min_products). A model with 3 products is a thin page whether its URL
--     has a question mark in it or not.
-- ───────────────────────────────────────────────────────────────────────
SELECT
  p.brand,
  p.model,
  COUNT(*)                        AS products,
  COUNT(DISTINCT p.color_family)  AS colours,
  CONCAT('/collections/vanity-models/',
    TRIM(BOTH '-' FROM
      REGEXP_REPLACE(LOWER(CONCAT(p.model, '-', p.brand)), '[^a-z0-9]+', '-')
    )
  )                               AS would_be_url
FROM products p
WHERE p.is_active   = 1
  AND p.category_id = 1
  AND p.model IS NOT NULL AND p.model <> ''
GROUP BY p.brand, p.model
ORDER BY products DESC, p.brand, p.model;


-- ───────────────────────────────────────────────────────────────────────
-- Q1b. FALLBACK if REGEXP_REPLACE is unavailable — the counts without the
--      slug. This is the part that actually answers Q1.
-- ───────────────────────────────────────────────────────────────────────
SELECT p.brand, p.model, COUNT(*) AS products
FROM products p
WHERE p.is_active = 1 AND p.category_id = 1
  AND p.model IS NOT NULL AND p.model <> ''
GROUP BY p.brand, p.model
ORDER BY products DESC;


-- ───────────────────────────────────────────────────────────────────────
-- Q1c. THE HEADLINE NUMBERS, one row.
-- ───────────────────────────────────────────────────────────────────────
SELECT
  COUNT(*)                                        AS model_pages,
  SUM(products >= 25)                             AS could_be_indexed_25plus,
  SUM(products <  25)                             AS thin_under_25,
  SUM(products <   5)                             AS very_thin_under_5,
  MIN(products)                                   AS smallest,
  MAX(products)                                   AS largest
FROM (
  SELECT p.brand, p.model, COUNT(*) AS products
  FROM products p
  WHERE p.is_active = 1 AND p.category_id = 1
    AND p.model IS NOT NULL AND p.model <> ''
  GROUP BY p.brand, p.model
) t;


-- ───────────────────────────────────────────────────────────────────────
-- Q2. MODELS WITH NO BRAND — each would get a bare slug.
--     Expect zero rows. Any row here is a data defect: products.brand
--     should always be set, and the fix belongs at the import, not in the
--     URL rule.
-- ───────────────────────────────────────────────────────────────────────
SELECT p.model, COUNT(*) AS products
FROM products p
WHERE p.is_active = 1 AND p.category_id = 1
  AND p.model IS NOT NULL AND p.model <> ''
  AND (p.brand IS NULL OR p.brand = '')
GROUP BY p.model
ORDER BY products DESC;


-- ───────────────────────────────────────────────────────────────────────
-- Q3. SLUG COLLISIONS — two model pages that would share one URL.
--     Expect zero rows. The brand suffix makes this almost impossible, but
--     not quite: the join is a hyphen and both halves can contain one, so
--     ('A B','C') and ('A','B C') both give a-b-c. scripts/dumpModelSlugs.js
--     refuses to write the snapshot if any exist.
-- ───────────────────────────────────────────────────────────────────────
SELECT slug, COUNT(*) AS pages, GROUP_CONCAT(CONCAT(model, ' / ', brand) SEPARATOR ' || ') AS clash
FROM (
  SELECT
    p.brand,
    p.model,
    TRIM(BOTH '-' FROM
      REGEXP_REPLACE(LOWER(CONCAT(p.model, '-', p.brand)), '[^a-z0-9]+', '-')
    ) AS slug
  FROM products p
  WHERE p.is_active = 1 AND p.category_id = 1
    AND p.model IS NOT NULL AND p.model <> ''
  GROUP BY p.brand, p.model
) t
GROUP BY slug
HAVING COUNT(*) > 1;


-- ───────────────────────────────────────────────────────────────────────
-- Q4. NAMES THAT WOULD SLUGIFY AWKWARDLY — accents, quotes, slashes,
--     ampersands, or anything outside plain ASCII alphanumerics and spaces.
--
--     These are the rows where this SQL and modelSlug.js may DISAGREE (see
--     the note at the top), and the rows most likely to produce an ugly or
--     ambiguous URL. Expect zero. If there are any, read them before step 2.
-- ───────────────────────────────────────────────────────────────────────
SELECT DISTINCT p.brand, p.model
FROM products p
WHERE p.is_active = 1 AND p.category_id = 1
  AND p.model IS NOT NULL AND p.model <> ''
  AND p.model NOT REGEXP '^[A-Za-z0-9 ]+$'
ORDER BY p.brand, p.model;


-- ───────────────────────────────────────────────────────────────────────
-- Q5. CONTEXT — does each model have content to put on its page?
--     model_groups holds the description, meta_title and meta_description
--     that admin/model-edit.ejs already edits. A model page with no
--     description is a thin page regardless of its product count, so this
--     is the other half of the indexing decision.
--
--     LEFT JOIN on (model, brand) — the pair, not the name. model_groups
--     has UNIQUE KEY uniq_model_brand (model_name, brand).
-- ───────────────────────────────────────────────────────────────────────
SELECT
  t.brand,
  t.model,
  t.products,
  CASE WHEN mg.id IS NULL                             THEN 'no model_groups row'
       WHEN mg.description     IS NULL OR mg.description     = '' THEN 'row, no description'
       ELSE CONCAT('description: ', CHAR_LENGTH(mg.description), ' chars')
  END                                                 AS content,
  CASE WHEN mg.meta_title IS NULL OR mg.meta_title = '' THEN '-' ELSE 'set' END AS meta_title,
  CASE WHEN mg.custom_image IS NULL OR mg.custom_image = '' THEN '-' ELSE 'set' END AS custom_image
FROM (
  SELECT p.brand, p.model, COUNT(*) AS products
  FROM products p
  WHERE p.is_active = 1 AND p.category_id = 1
    AND p.model IS NOT NULL AND p.model <> ''
  GROUP BY p.brand, p.model
) t
LEFT JOIN model_groups mg
       ON mg.model_name = t.model AND mg.brand = t.brand
ORDER BY t.products DESC;


-- ───────────────────────────────────────────────────────────────────────
-- Q6. THE OPEN_ITEMS 11a QUESTION, answerable now:
--     is JM's "Collection Name" (which the importer slugifies into
--     collections.slug) the same string as products.model?
--
--     If every row comes back matched, the `collections` table is a
--     ready-made slug store and step 2 could read it instead of the JSON
--     snapshot. If not, it is a third naming authority and stays parked.
--
--     Purely diagnostic — the answer does not block step 2 either way.
-- ───────────────────────────────────────────────────────────────────────
SELECT
  COUNT(*)                                              AS distinct_models,
  SUM(c.id IS NOT NULL)                                 AS matched_a_collection_row,
  SUM(c.id IS NULL)                                     AS no_matching_collection_row
FROM (
  SELECT DISTINCT p.model, p.brand
  FROM products p
  WHERE p.is_active = 1 AND p.category_id = 1
    AND p.model IS NOT NULL AND p.model <> ''
) t
LEFT JOIN collections c ON c.name = t.model;

-- ...and the ones that do not match, by name:
SELECT DISTINCT t.brand, t.model
FROM (
  SELECT DISTINCT p.model, p.brand
  FROM products p
  WHERE p.is_active = 1 AND p.category_id = 1
    AND p.model IS NOT NULL AND p.model <> ''
) t
LEFT JOIN collections c ON c.name = t.model
WHERE c.id IS NULL
ORDER BY t.brand, t.model;
