/* ============================================================================
   DOCUMENTS TO BUNNY — spec sheets and assembly instructions
   2026-09-22

   product_documents held 19,960 images.salsify.com links (5 doc types) to
   only 475 distinct files. All 475 were downloaded, checked (valid PDF header
   and end marker) and uploaded to the pull zone as docs/<file>.

   ⚠ PREREQUISITE — deploy the importer change FIRST ⚠
   Commit "importer: keep spec sheets on Bunny" teaches replaceDocs() to use
   the Bunny link for any file in doc_cdn_map. Without it, the next James
   Martin feed drop puts every Salsify link back.

   Steps 1 and 3 are read only. Step 2 creates and fills the map. Step 4 is
   the write. Step 5 verifies.
   ============================================================================ */

/* --- STEP 1 — before ------------------------------------------------------ */
SELECT
  SUM(url LIKE '%images.salsify.com%')                AS on_salsify,
  SUM(url LIKE '%images.bathroomvanitiesoutlet.com%') AS on_bunny,
  COUNT(*)                                            AS total_rows
FROM product_documents;
/*  Expect on_salsify = 19960. */

/* --- STEP 2 — the map ------------------------------------------------------ */
CREATE TABLE IF NOT EXISTS doc_cdn_map (
  filename   VARCHAR(191) NOT NULL PRIMARY KEY,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO doc_cdn_map (filename) VALUES
('492eeed0fca77405f90628996e4a488ef820536d.pdf'),
('5a0b70ef7508e31d1705eaf8fabe47d1671883ed.ai'),
('5e872accc89a9a70764431bce584179797df232a.pdf'),
('724341b01cfe7b49aa3ff4ebd021681927968dcd.pdf'),
('7608697a50060fc3ff66b672362b49f61d5eae52.pdf'),
('8a2d6811b297080457353aa9bd5efd6e213ddb11.pdf'),
('a1zwn5hzqzdshu5bvhyq.pdf'),
('a5vkgld6c7obcts7eyad.pdf'),
('a8g4krvi0fpsyvs9xsn9.pdf'),
('adipif3qudkqyjfctolj.pdf'),
('aepq1m8ckt0eyyfidwlm.pdf'),
('afffjj0jqgctkskwnlib.pdf'),
('afye96cmwxonnh2t5hbn.pdf'),
('agq0j2tu0nkp9h0ktstr.pdf'),
('ahiq26suwznwm3kl1jd2.pdf'),
('ajt2utduaqkfbi1rlz6o.pdf'),
('as7hwiloss5dxfwbu8fz.pdf'),
('axtpsks9tyaosegoxqip.pdf'),
('ay0wts62rkhzw1gtcjfl.pdf'),
('ay5fdgbrl4jocdzkffag.pdf'),
('b0y3nli8pm6pab2bvouk.pdf'),
('b1wrvozukfwtprdoikxz.pdf'),
('b2kwxjhpzzyrqcxekv2v.pdf'),
('b69pxomebcnu07szthgv.pdf'),
('b6minkrvkjfqmzudv7r6.pdf'),
('b80cvchxhvydhotnd6qr.pdf'),
('b9xesdwywcx6beeh1vf4.pdf'),
('balaijde86doml6amy4t.pdf'),
('bc9yyp5vr4srunz8lnsj.pdf'),
('bfjr7sgowkd5cwviwtce.pdf'),
('bi2e21hcszxf1hslbkh7.pdf'),
('blljsnpt1ljzqlrtljgf.pdf'),
('bonraldcx1dzia0sunqd.pdf'),
('bqcp1qe01uvowkifqffq.pdf'),
('bqsbvxga3viaxybdh3fp.pdf'),
('bt8ttphqm7qka5lc8tjg.pdf'),
('bv43nvefwor1fsi6f7k2.pdf'),
('bzi9cs731orqxlo1qzzn.pdf'),
('c212ullhzuzygcu3tepp.pdf'),
('c3orcwktcrdjx5jsa7bc.pdf'),
('cdokfxvwmlocgh9bjmm3.pdf'),
('cdxozqxhw5mv5llwm7aj.pdf'),
('cevu1irj8xqdmjlkol5o.pdf'),
('cf3r4fns1uajyjfavwfy.pdf'),
('cgv8a17aw9uhhqiunsp9.pdf'),
('chef30826u1tmsy4ynwt.pdf'),
('civ7gyzzmpg7asuspfk3.pdf'),
('cninxckycqmah0w1upkd.pdf'),
('coercpahsr0vjapicf3q.pdf'),
('cssyaez5ivz3gvwhcfcy.pdf'),
('ctf7qcx8xegqnpi3wnqw.pdf'),
('ctghg5vf9kcxq43hy7zi.pdf'),
('cwpvkpjzolofycimq0ng.pdf'),
('cxoast56xyq27fmn7t0i.pdf'),
('d1ghpj1nofsulmkxkasd.pdf'),
('d2nhekgoxdugfv4dzyqj.pdf'),
('d4v3hbwwmtdajcyooi6k.pdf'),
('d5ajtzhtnwb3bnednbaq.pdf'),
('d6dhparx59c7gjfinqmo.pdf'),
('d7r0sibqbrcm4i2mbwxw.pdf'),
('db9jmbgeemuptn2fvbxv.pdf'),
('dcbivz2f14k3qrdxoxs3.pdf'),
('dentxzlzcpor6arusiqt.pdf'),
('dit5odlu1s0t4beo21jm.pdf'),
('dj3wvafqf6p9fzqfffml.pdf'),
('dl9wdwiethcqmh8rrvwp.pdf'),
('dlc6anpbd2eglid1q0mm.pdf'),
('dojsmta5uvdrkr5eip5r.pdf'),
('doyxkrxvzma3v7qkojhx.pdf'),
('dpihf2hmtov5e5bewvtu.pdf'),
('dqmerzb0hymft2vsyg9w.pdf'),
('ds3qrasnphiylj8nmmad.pdf'),
('dsczbmj28bp4tpsopcbu.pdf'),
('dt2z5qpqhdj9zdlthteh.pdf'),
('du3baehl3tebv6iluhhd.pdf'),
('dvd6wggcissxwqs9moy8.pdf'),
('dvuwsx4akz7dthocgrn9.pdf'),
('ebhqatef4fnhqh1nzrvk.pdf'),
('eei7eqvxucbgqjtjifml.pdf'),
('efj38tarzdmroradlib7.pdf'),
('efnvija2hpdytwacauyi.pdf'),
('efpn146uv3qh1pq1d3vb.pdf'),
('eii9cd9ciel8a8vdmcef.pdf'),
('ej3r7rfkpqbrk0jycy94.pdf'),
('el5mhg08ftvmpgyx9pqs.pdf'),
('emal03waqiy2dvgfasuk.pdf'),
('es2zgltk52bwiqsvbcbs.pdf'),
('eth2qgfpsvfwtskjebfw.pdf'),
('eu7x7ksoujftjugiq8wn.pdf'),
('exbuisu8wsmtqeqcrpf8.pdf'),
('f6b4y3sc8dygdiqqc91n.pdf'),
('f6jqayjdg6aoycmobanw.pdf'),
('f8jfnwahp3hlsltit72s.pdf'),
('faakqysv8kcmmizgot1u.pdf'),
('fbbrgm3ck2yupdtvfmub.pdf'),
('fbgberqas11mwhwrv0tt.pdf'),
('fbpu1b0qfzv276ufgflw.pdf'),
('fffprtvbxysgqhmtjtwb.pdf'),
('fhmkzal7yfzanxgfrisp.pdf'),
('fiajcuf96ha8ylcd7qs2.pdf'),
('fibl0n4kdexztlnlowxu.pdf'),
('flik96twtzohvedd2wyx.pdf'),
('fmct4dghtfbhvtau3lob.pdf'),
('fmr5pvih2poa90w85i5c.pdf'),
('fmv52yyfzfoqfne1sijh.pdf'),
('fnsaxp9cfgjteje2nh1g.pdf'),
('ftkxfbpqfgxewdh5na8k.pdf'),
('fwkndoij8yiml4hvqhzh.pdf'),
('fy9ikjpgq57rj1fen0li.pdf'),
('g4hjj01kx3dgntydiu8m.pdf'),
('g8dywkwbk8y2eu2lhiil.pdf'),
('g8q0cpncdmkhvlftwelt.pdf'),
('g9b83kcqieon5yksbqed.pdf'),
('g9knse9hec9xwfublmnc.pdf'),
('gawdmgt3jhpu0pdmd5mq.pdf'),
('gbcdlxizdboixpaiu3kh.pdf'),
('gervqzks7laqrz7xwafk.pdf'),
('gfous0m3dhvhcfokbkkp.pdf'),
('ggiognzcnhq7grlnggff.pdf'),
('ggwdbj60kwxsjdgcktmj.pdf'),
('gi6artqzy2hiffbfzncp.pdf'),
('giow80o2tujxewqagdyj.pdf'),
('gjfjcdfpv71ent300ma1.pdf'),
('gjj0icfpomorwjyoqoeo.pdf'),
('glrtpophxltbkg8x6cnz.pdf'),
('gmmsedufgel0gynidxao.pdf'),
('gp7upt2kglbsupoiz8dl.pdf'),
('gpqhyyutmrjmpip3eisj.pdf'),
('gpvyvfs36juwycgo2jip.pdf'),
('gqo9suhkypudemy8j6pv.pdf'),
('gr7cksiw2a0fw9hpi1ii.pdf'),
('gvowop6syw8tvtlhkfqy.pdf'),
('gx9kovtlqlzjkrk8i2qq.pdf'),
('gxf5r2cbd15ofe1thsvu.pdf'),
('gxzobox9kyjfwqj9vlbw.pdf'),
('gy57tc9sujfgra621ki2.pdf'),
('gzq2c5exjskd8s1k1o6k.pdf'),
('gzy4gsoxilnx1mgk94sh.pdf'),
('h22ddkx85jo08qtv6wfu.pdf'),
('h7dti4nvfsxzvluiv7xr.pdf'),
('hapeznfm8slwtkxdlngv.pdf'),
('hcedythojxtzd2yn8st4.pdf'),
('hed1ybkwsr8clnootykp.pdf'),
('hfrzc4zvifqrwyklfv56.pdf'),
('hhgi0lq8z4efjv8kbl5f.pdf'),
('hkrtpkuxcrojec3qcztk.pdf'),
('hktgbgga2obt2dxcypod.pdf'),
('hkxem70hfwlsz60hcgrj.pdf'),
('holoqfnwuuyt5o7axb33.pdf'),
('hp75e0rhe6jkpzwd4tod.pdf'),
('hu4c9slrutfcy73nqcng.pdf'),
('hy7t2u6s6rwpazaxiuzf.pdf'),
('hzroneodu74u63ziysxa.pdf'),
('i5hkgaifkpeap6xkof5a.pdf'),
('i6akafms2xvj94hbu6do.pdf'),
('iandj7qjhhh937c8jbx0.pdf'),
('iclzctdcdzpqvol8iy3p.pdf'),
('icqemqnlyczbfqt8qhig.pdf'),
('ijdnszyj3bxfqbiytdre.pdf'),
('ijw1oxwkchdf6etk5dx7.pdf'),
('ikifaawmmhtwnet3lpa5.pdf'),
('ipjfpendczxsmpyemvep.pdf'),
('iptrzqylsmznlj1puwso.pdf'),
('isv2f1lrrtrc3fhgtori.pdf'),
('ittueinlkuxkkf0gffhn.pdf'),
('ivepicrsnsjs0sbpgwdi.pdf'),
('iwpihaocfzahejehzapu.pdf'),
('j11dpz4iumbrkypobrzt.pdf'),
('j406qbovu1lc9urp2n4p.pdf'),
('j7qrufthbecvblutjfio.pdf'),
('j8bvbscctcd979ad7e1u.pdf'),
('jaaq40zzifro7zb2yl2q.pdf'),
('jdqfpvnyc4otb2w7szdu.pdf'),
('jgeqvq3c57wylkhctpsk.pdf'),
('jgo5ycmexa1dwevz9wxh.pdf'),
('jhamdhwiekzehbgh9sot.pdf'),
('jilw5kqd3yc5cjglp4vt.pdf'),
('jkpbcbdafps0bs1jderm.pdf'),
('jnfjholdvlmudeqboull.pdf'),
('jnggxo0mqc0vqw5oxbkl.pdf'),
('jnhhjup6qwezaafpbafx.pdf'),
('jnz6535boyu3gymwnmsx.pdf'),
('joigv7nptbmfgfcwjiky.pdf'),
('jrfz4me8s9ki3kglxga3.pdf'),
('jruiomteuhn4u6wmqk5b.pdf'),
('jxevq9vbfu0or74tundo.pdf'),
('jxpbeq1w4fsu665mzpud.pdf'),
('jyauylzwfsngddrmwcio.pdf'),
('k1zcm4gbtkwupbx0qheo.pdf'),
('k31sosdngeeuqkk9x9is.pdf'),
('kabwjijoceueuwyu6vc8.pdf'),
('kaecg6qhtkdm6yhog76k.pdf'),
('kayg7ciocyzk2iholmyy.pdf'),
('ke6g64to1uces5wzz7u6.pdf'),
('keklk5sbxgr87muja41j.pdf'),
('kfmatqyeto2t26ubcrwk.pdf'),
('kjsuxydaolxnuqo5tj8k.pdf'),
('kkvxp73mptojgzq362lj.pdf'),
('kmtyop5ye3mu6vjmzgyx.pdf'),
('knjyifyoplpbm6abgbyo.pdf'),
('kotjyw11h2tj5zktd5wr.pdf'),
('kqhlacvygtyfsx3tf4k8.pdf'),
('krfypoegjmmvetomfxrq.pdf'),
('krg548w4n2qehqpuzesv.pdf'),
('ks7c6hl2hr1h8iufsvtb.pdf'),
('kv5wmjukjnlcggtz70yg.pdf'),
('kxjduzhyttq5r4pytmoy.pdf'),
('kxoncnhmve91t8gor4ry.pdf'),
('kz1zxktpuz8cnjodbwjo.pdf'),
('kzljk6gbk0i4ujqowhkd.pdf'),
('l8muhnj9lfiewizhvtl6.pdf'),
('l9yoqocr2zb7mjxtq0kp.pdf'),
('lcjoyi5nf7zpfln9tznl.pdf'),
('ldbqcpgnw1mpvkepmarw.pdf'),
('lfho0ocpqkvkzogqtxmc.pdf'),
('lgwauzilnldctzplln7h.pdf'),
('loth6lff8ynl05ofpx6g.pdf'),
('lpofklktemmqpzvhingr.pdf'),
('lr7hr4o1ocbs5gcrr27j.pdf'),
('lsapdjsxb4rvyfdfcb0b.pdf'),
('lukxd0tok3nzsychoqjj.pdf'),
('lv9qyadpss9nhkvjcdv3.pdf'),
('lwhguvrrynu5h9kcf0dg.pdf'),
('lwixmvvqn5obe2eeocxp.pdf'),
('lygilcrfnwxwv1dvva7x.pdf'),
('lzsm3ew7oaxztsvjcywf.pdf'),
('m6oce53zmk7qtprfbho6.pdf'),
('m98fsqq9umt2xgdrhmgv.pdf'),
('mclxdzib7n8vcic2ko0x.pdf'),
('mikqvtuaih0dfyplt0za.pdf'),
('mmhpfqxflwewsdrxwpvx.pdf'),
('mmyjc6fik2xaervnn1ih.pdf'),
('mnqbkxartsm72kjku9oa.pdf'),
('mp6vvejradmtthpzcvoc.pdf'),
('mpiji3gobcqb5licxylo.pdf'),
('mqnerqsdgczi1zcucbia.pdf'),
('mtgramjg309ejkjpw8tj.pdf'),
('mvexu9n4rbv6xqhxjiia.pdf'),
('mx4dgdgtx9jh0husabr5.pdf'),
('mxmt4rpyitwl0qx1vhtu.pdf'),
('mxpn4jk7aelbr22dsn6z.pdf'),
('mxwwmpc7tzudhau0e5ld.pdf'),
('mxzxkxtae8qdexujtkze.pdf'),
('mzpt9bobwxh2fgrnspuk.pdf'),
('mzvzomia6opjjzrr4afv.pdf'),
('mzy4mhht1gplsvdfye28.pdf'),
('n7sisokvu7acmblmluo4.pdf'),
('n8v7j2nlq9idnzmj3g5a.pdf'),
('nblp8bmbuk90z5rclpxa.pdf'),
('ndeqnxmyq7ynokxm5zmt.pdf'),
('ndpnqvfc9yvtsialsj6c.pdf'),
('nepd44jvfsqprzpawneo.pdf'),
('nfalnhra6ohym5roclpc.pdf'),
('nfli7lnkkiinerba24h6.pdf'),
('nhvhhlbgofhluwzwf4ua.pdf'),
('ninrguaeadlpjjy7prst.pdf'),
('nizzzsqqooae17hgg47k.pdf'),
('nlychfmkrckqxqmrk0lk.pdf'),
('nmk3apknawzogu1seewg.pdf'),
('no6xpwkjqjoawgifbsaa.pdf'),
('nofi4lla4whkcb8vvbqm.pdf'),
('nqyjvph1grfleizsesaw.pdf'),
('nu3jbtdh5gpfvcjsl9tq.pdf'),
('nuknd8m1i5ereppsjlhz.pdf'),
('nvzsz4tlptqfdshhgbmj.pdf'),
('nyju5f2cxhfu3w4kkjw9.pdf'),
('nzl4bh9httodbjgge2ai.pdf'),
('o8svweslsjm7ugzaztrp.pdf'),
('o9lb8xmnxxlmvtiwirwd.pdf'),
('oae3shntzlfdjswi4hph.pdf'),
('obqaq8cpgdqa6ec7mjaq.pdf'),
('obzh2mvrjioanyrcwkcw.pdf'),
('ocnzdnxihgryrvhnj4hq.pdf'),
('odgs2zvvsbwxphmoj7tj.pdf'),
('ofckjaxqssnmgzqjyxan.pdf'),
('og5cgl6x3fxw2slplilv.pdf'),
('ogjnbjbxhix6iu7kjnjo.pdf'),
('oijwlibwuyq6rcyb0xrg.pdf'),
('ojheaq6gaknozw1kim9c.pdf'),
('onfmvye2tyygapej89p5.pdf'),
('onqw3hiiuzdjtya4otke.pdf'),
('opicxlvuahxdlnalhnbm.pdf'),
('opv9wckblc8uwha6tbby.pdf'),
('oqoanjpt7mzvrtkzmrdh.pdf'),
('ore673glvwhtlk0iq6wl.pdf'),
('orlhkpazft2bzwiceps0.pdf'),
('osa5o8bbwqhcyhszd6v9.pdf'),
('otsa1foxffshijeosa6d.pdf'),
('otyrbntnwbyxgn0dpqqk.pdf'),
('otyrqq4kshfx2jdsl1ys.pdf'),
('ous4foq71lbmgewe4a0v.pdf'),
('ouzs7kl0thnkkue95qz5.pdf'),
('ovxv3bceqpf3iymubmz5.pdf'),
('oxpzzfepvgeewefxpbxa.pdf'),
('oxypbaivsvcgcsqwyumm.pdf'),
('p0l2tb5qsumskp9gswx8.pdf'),
('p3xdbijal5kl5ouovon0.pdf'),
('p8x7h1r4rv41cxzgboux.pdf'),
('p9fe1m78kuwnieojqz3c.pdf'),
('pbbtqwcqyvfvuqy5luvh.pdf'),
('pbh29l1oygv7djoac20r.pdf'),
('pdikcwnzuazmoilblhfo.pdf'),
('peoxnbp2r3rxptgdtmw8.pdf'),
('perajdysao9one19a02s.pdf'),
('pes2mslu4tiuj5dwfsj3.pdf'),
('pgtubq2eembiu2xmooo1.pdf'),
('phjk1gtw6ufrfdqpmphb.pdf'),
('pibhu9p6fjxo8j4acr7j.pdf'),
('pigoiuvtgqxio59fribm.pdf'),
('pst0miqlayanbcjpk15m.pdf'),
('pu9z8qmsgqogbqujwjfx.pdf'),
('pukgmdkprdbn0t4jypoi.pdf'),
('puoa14xzbcv8ynag9lyi.pdf'),
('pvnysocrbtvdvoxflsw9.pdf'),
('pwuyxetllcqw5qwkhgtx.pdf'),
('pzgxc3awih3y8fo3p7cf.pdf'),
('q4c6fiup4broud5urcoj.pdf'),
('q6rk6kg3fiflqmamuzgp.pdf'),
('qgfqtqttkfog2g3gnx35.pdf'),
('qhmhu0s5k3d7rjbvsjvb.pdf'),
('qjkkbhetaf7kjpclcn4r.pdf'),
('qmzh5bfkabnbwe5oedek.pdf'),
('qtyavjx2kkrlk9gddnng.pdf'),
('quxhvnjnswi1qcmfhxh6.pdf'),
('qwh8td6hblrsblszpd9v.pdf'),
('qwlnubv3jfurlyur3knq.pdf'),
('qykpozofevmznz2rii3v.pdf'),
('qznpgk4vq92sece19nam.pdf'),
('r0gvmpmncdtf00ifv00e.pdf'),
('r2mbdcjybij4ovxrjwtw.pdf'),
('r2mfxlmbl7jeqbrtaxzk.pdf'),
('rddm6svyqzb64w80h1w4.pdf'),
('rezeknkxmxgljkgzadsr.pdf'),
('rid29kg9rxjizap7nem0.pdf'),
('rj4a4s8gf2yse5xw588q.pdf'),
('rkpczq5zo3ccsflkcr5l.pdf'),
('rktpdmh6qydtb3w8zl1d.pdf'),
('rlqtyksow5kunnrvuexo.pdf'),
('rlzycfwrcojiqxdx3zvh.pdf'),
('rmfumgbnquvxa2jyzspm.pdf'),
('rpmdkuwaz3sc9uckxvtc.pdf'),
('rsxckhcxfpyt2ck6mei2.pdf'),
('ruygdtxpcvqlvqleadhy.pdf'),
('rxazjnmyzaatbndflowt.pdf'),
('s0yplu2sxktmhyrwfjhw.pdf'),
('s38npflvry0vf9jhlwqe.pdf'),
('sbho7xyn1d9ssftmht8f.pdf'),
('sdggxhg8axzfwpqmyd3r.pdf'),
('sgvyro6hgxhjlbn1ly4u.pdf'),
('sm65aecptn9yv2hpmqu5.pdf'),
('srxx6rs3txeewxlibevz.pdf'),
('ss3rbpovhtw1wea35djq.pdf'),
('ssvh1hkd7fqqbyhpvx8m.pdf'),
('su9i823wqqoniblxyfgq.pdf'),
('sw1jyw8n9jkez5ulzolj.pdf'),
('sxp0lkjouaeseiqniswh.pdf'),
('ta1e4dgz0ucqwytb4qnm.pdf'),
('tbeoxg6tjzdq5ore4qfn.pdf'),
('teogu9iejm1yyvndfs2w.pdf'),
('thtzgosexibap3wmkvvm.pdf'),
('titz2h8t2ibg3sng0fyg.pdf'),
('tiulu0j8dz0txa0o1ta4.pdf'),
('tkkgypa6jczdwdtv0hv9.pdf'),
('tlkpickte8vvqvjo9kgl.pdf'),
('tmsvzxdbydgowppgavcv.pdf'),
('tonlfehf6ouho2uk1l6v.pdf'),
('tq12uuvgzgerimdif4rz.pdf'),
('tsoud9wucdvakc3y5now.pdf'),
('tv5rlolkn49dcq09lczl.pdf'),
('tvcj1kes5jvfae7lztwm.pdf'),
('twuvdceagzlwojaufllu.pdf'),
('tyb2tssrveth1zvugfag.pdf'),
('tyyi8ofxi4aheneespo6.pdf'),
('u1z0boo0ctgr1ghpokwq.pdf'),
('u3jyka2l6foxrrmartdi.pdf'),
('u7rytz0x7ab2x6z2ay2b.pdf'),
('ubzpmhp7nlyjhgkijkke.pdf'),
('ucmi6gsvcqkldwkry7h1.pdf'),
('uiqbpxe65nodcsbivo7h.pdf'),
('ujalooqfl5qmqlhosdls.pdf'),
('ukmwzhj1c4vfyvhf9yfn.pdf'),
('uko0j3trsk58ajvdkqug.pdf'),
('ulollhbqk5jf4t3czbl6.pdf'),
('ulso860igtwgpvohe3ho.pdf'),
('umcgd9nkcun7glnkkxeq.pdf'),
('umojcusnr4kpcdkoitwx.pdf'),
('unajcpzmsqlxofu9vqrc.pdf'),
('uokelyi20pkwhmhdiz6g.pdf'),
('uqtwulatwvkouae5wdoa.pdf'),
('ut0smpfkfc5npagwtjvg.pdf'),
('v0mewdyssodjqi8vahgw.pdf'),
('v2tvyzgpbo5fyb8ls9is.pdf'),
('v2umdwi3m8jxlldjd4at.pdf'),
('v5djgyt47e8n1mzvxc3s.pdf'),
('v5kzlpdvwowjscepwjfp.pdf'),
('v8cfyavqhkyvz7ja8y2a.pdf'),
('vehwpgpz83cskzivd1tt.pdf'),
('vfunm0japfy6cevklkue.pdf'),
('vfzxopjezlbzfwoa3vaw.pdf'),
('vjxxe1ccv2rmaizamtta.pdf'),
('vnlnyyutsm92koufmn6h.pdf'),
('voysyh9drzjiw7yuuon8.pdf'),
('vpjvc8yqsowdcgngddon.pdf'),
('vqdhk4flhqop5rrunlho.pdf'),
('vsxlpdgm4j2oc5aecapx.pdf'),
('vubnido3maiqdyovw6ea.pdf'),
('vvyt3qd8br1lu2othie0.pdf'),
('vwbuj5fkyerpodmw9ngd.pdf'),
('vy8tcy0il92g9beq1phc.pdf'),
('vyhaqtbpfv5xx0ik6naw.pdf'),
('w1qalksde5sdhd2kzguu.pdf'),
('w2p6abi7cnfoxefhlytc.pdf'),
('w5dmibjyaqjsrtm58zih.pdf'),
('w6w7fo17yc2kudvfmaqz.pdf'),
('wap6yehc4aph9gbtyirq.pdf'),
('wb6wi3veiycqqqpqurrz.pdf'),
('wdtenzi2dpfts7nwzjcn.pdf'),
('wlvb2wv5omgeeqqwnpdt.pdf'),
('wo2h0kfhk4ptxjj4c8ia.pdf'),
('wpqec8sqpkro6utkwnue.pdf'),
('wvzonejndw9cmpffomxv.pdf'),
('wzbgrfyku3knzza8fu6c.pdf'),
('x1cozsxyvwsb4p036fe8.pdf'),
('xccqyx3jvbdyijv01hvj.pdf'),
('xdjby9uk1wbkkm1hskr3.pdf'),
('xeydo2jg0wxk5g6nxpl2.pdf'),
('xiepjlumcyzovzsqhsbb.pdf'),
('xjoqb2nptqfgk8gvwslu.pdf'),
('xnonzy2wlejkys0z7ccl.pdf'),
('xoexhgrfe7dyt1qdjjxj.pdf'),
('xpsjebuydnl54igd6tcp.pdf'),
('xqeigvjngnbdvhb2xyfk.pdf'),
('xs4hovmze02gnnlgpy4y.pdf'),
('xviarhk273zspj7akyfr.pdf'),
('xvqudz1v9hj1y2ngtkeo.pdf'),
('xw8vsbygicf08rvk2mbx.pdf'),
('xy5oi3e4axxxzybhlhdf.pdf'),
('y5dpl3hahplmnvjuqwsx.pdf'),
('y97xdxjvvnscl1l1maqg.pdf'),
('ya8ss6ly13yolldsc2zx.pdf'),
('ye9k3vssv9vx9lscfxtt.pdf'),
('yhnukteooh8nwptxsdy8.pdf'),
('yltgw2gcccmfdpvpcigo.pdf'),
('ymoppyqav4sihtnbwptf.pdf'),
('yneiwtmmtus4xvw60szp.pdf'),
('ynewprmjxfkwn4g1s1gz.pdf'),
('yptay7u9jpnumxeuorti.pdf'),
('yrpusp29jdvnhp0jlhmv.pdf'),
('ystbar2vtiobuejazsya.pdf'),
('ytc6fyqo6z3dgatgnchv.pdf'),
('yw23s0rdlyn8bp2ggwlg.pdf'),
('ywyjrdaejo2dwyj4g9qf.pdf'),
('yxfll6zjmci1wjgez4uq.pdf'),
('yxmbjlh6iqscvbtvbwy7.pdf'),
('yxqzgjiocrn8qa3zxr0x.pdf'),
('yyptc334v5vkozivaxlk.pdf'),
('z0k0us5eaq4jemsh8mo5.pdf'),
('z0vdeaq6egvgqdjfuhh0.pdf'),
('z7hdkzmqmc9r5vdhzivz.pdf'),
('z9fpywwprocefo8anz5w.pdf'),
('za8imub7lnmv3uv7kwfq.pdf'),
('zahofrk97iafrqf2kxai.pdf'),
('zamqmr63kgkwxinqehni.pdf'),
('zc0zqpwrfk0olxzr4ay9.pdf'),
('zf4lc3hmgsonc9rnzima.pdf'),
('zgetaozdwflsbgd1zgtq.pdf'),
('zgxqdhyybgzxy54fanhm.pdf'),
('zjx8o1raox4v3zfdtfuh.pdf'),
('zkdwcjotkopi3xelrlwv.pdf'),
('zoydrjsyispntzl4v5xm.pdf'),
('zru1cxi4ghhpnpgbko5t.pdf'),
('zt3l0nc2hup2nvn3xcxw.pdf'),
('ztqrvacvwika0yus4y29.pdf'),
('ztsw6vuvbrvvxt6nsqkf.pdf'),
('zwgty7uyq0cgjunt3yww.pdf');
/*  Expect 475 rows inserted. */

/* --- STEP 3 — rows that WILL be repointed (read only) --------------------- */
SELECT COUNT(*) AS rows_with_a_mapping
FROM product_documents pd
JOIN doc_cdn_map d
  ON d.filename = SUBSTRING_INDEX(SUBSTRING_INDEX(pd.url, '?', 1), '/', -1)
WHERE pd.url LIKE '%images.salsify.com%';
/*  Expect 19960. */

/* --- STEP 4 — THE WRITE ---------------------------------------------------- */
UPDATE product_documents pd
JOIN doc_cdn_map d
  ON d.filename = SUBSTRING_INDEX(SUBSTRING_INDEX(pd.url, '?', 1), '/', -1)
SET pd.url = CONCAT('https://images.bathroomvanitiesoutlet.com/docs/', d.filename)
WHERE pd.url LIKE '%images.salsify.com%';
/*  Affected rows should equal STEP 3. If lower, stop and say so. */

/* --- STEP 5 — verify ------------------------------------------------------- */
SELECT
  SUM(url LIKE '%images.salsify.com%')                AS still_salsify,
  SUM(url LIKE '%images.bathroomvanitiesoutlet.com%') AS on_bunny,
  COUNT(*)                                            AS total_rows
FROM product_documents;
/*  Expect still_salsify = 0. */

/* --- ROLLBACK (only if Bunny documents fail to load) ----------------------- */
/*  There is no stored copy of the old signed URLs (the s--xxxx-- part), so a
    rollback is: re-run the James Martin import with doc_cdn_map emptied
       TRUNCATE doc_cdn_map;
    which re-inserts the feed's Salsify links. Prefer fixing the Bunny object. */
