ALTER TABLE orders DROP COLUMN IF EXISTS payment_auth_code;
ALTER TABLE orders DROP COLUMN IF EXISTS payment_avs_code;
ALTER TABLE orders DROP COLUMN IF EXISTS payment_cvv_code;
ALTER TABLE orders DROP COLUMN IF EXISTS payment_afds_code;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_score;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_status;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_ip_vpn;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_ip_tor;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_ip_proxy;
ALTER TABLE orders DROP COLUMN IF EXISTS fraudlabs_email_risk;
ALTER TABLE orders MODIFY COLUMN payment_transaction_id VARCHAR(64) DEFAULT NULL COMMENT 'Stripe PaymentIntent id (pi_...)';
ALTER TABLE orders MODIFY COLUMN payment_status VARCHAR(20) DEFAULT NULL COMMENT 'pending, auth_only, captured, canceled, refunded, partially_refunded';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stripe_session_id VARCHAR(80) DEFAULT NULL COMMENT 'Stripe Checkout Session id (cs_...)' AFTER payment_transaction_id;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stripe_charge_id VARCHAR(64) DEFAULT NULL COMMENT 'Stripe Charge id (ch_...), referenced by disputes' AFTER stripe_session_id;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_risk_score TINYINT UNSIGNED DEFAULT NULL COMMENT 'Stripe Radar 0-99. NULL on Lite/Standard. NULL is not zero';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_risk_level VARCHAR(16) DEFAULT NULL COMMENT 'normal, elevated, highest, not_assessed';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_seller_message VARCHAR(255) DEFAULT NULL COMMENT 'Stripe outcome.seller_message';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_check_cvc VARCHAR(16) DEFAULT NULL COMMENT 'pass, fail, unavailable, unchecked';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_check_zip VARCHAR(16) DEFAULT NULL COMMENT 'pass, fail, unavailable, unchecked';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_check_line1 VARCHAR(16) DEFAULT NULL COMMENT 'pass, fail, unavailable, unchecked';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_authorized_at DATETIME DEFAULT NULL COMMENT 'When the hold was placed. Expiry warnings count from here';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_captured_at DATETIME DEFAULT NULL COMMENT 'When funds were taken. NULL while on hold';
ALTER TABLE orders ADD INDEX IF NOT EXISTS idx_auth_expiry (payment_status, payment_authorized_at);
