'use strict';

/* ═══════════════════════════════════════════════════════════════════════
   modelSlug.js — the one place a model-collection URL is decided

   WHAT THIS IS FOR
   `/collections/bathroom-vanities?model=Brittany&brand=James%20Martin%20Vanities`
   becomes
   `/collections/vanity-models/brittany-james-martin-vanities`

   Ten such URLs carry thirty internal links and cannot rank, because a
   parameterised filter canonicals back to its parent. Seobility flags them
   as "dynamic parameters"; the flag is a proxy for "probably a duplicate",
   which for these is true today and need not be.

   ── BRAND AND MODEL ARE SEPARATE PATH SEGMENTS ─────────────────────────
       /collections/vanity-models/james-martin-vanities/bristol

   Brand first, because that is how the catalogue is already segregated —
   Sam, 2026-10-03: "we currently segregate them by having Brand/model."
   The URL now reads as the hierarchy it is.

   THE CATALOGUE ALREADY COLLIDES, which is why the brand cannot be
   omitted. Verified against the live database 2026-10-03:

       James Martin Vanities / Bristol    300 products
       ER Vanities           / Bristol

   Two different vanity lines, same model name. I had claimed no collision
   existed, read off the ERV load file and the 10 models the crawl happened
   to show. Wrong: there are 45 model pages, not 10, and Bristol is in both.

   SEPARATE SEGMENTS ALSO REMOVE A WHOLE CLASS OF AMBIGUITY. An earlier
   version joined the two with a hyphen into one segment, which is not
   injective — both halves can contain a hyphen, so ('A B','C') and
   ('A','B C') both produced 'a-b-c'. The mutation sweep found that the
   collision detector was never tested, which is how the flaw surfaced.
   With a segment each there is nothing to disambiguate: two slugs that
   differ differ, and the detector exists only to catch two models whose
   names slugify identically within one brand.

   ── WHY A SLUG IS NEVER PARSED BACK ────────────────────────────────────
   `resolve()` looks the slug up in an index built from the real (model,
   brand) pairs. It does NOT split on hyphens, because model names contain
   them — "Mid-Century" slugifies to `mid-century`, and splitting
   `mid-century-james-martin-vanities` has no unambiguous answer. Any
   implementation that reaches for .split('-') is wrong, and
   gate_model_slugs asserts a hyphenated model still resolves.

   ── ALWAYS-SUFFIXING DOES NOT GUARANTEE UNIQUENESS ─────────────────────
   The join is a hyphen and both halves may contain one, so two different
   pairs can land on one slug:

       modelSlug('A B', 'C')   -> 'a-b-c'
       modelSlug('A',   'B C') -> 'a-b-c'

   Vanishingly unlikely with real model and brand names, impossible to rule
   out. Found by the mutation sweep, not by reasoning — the first version of
   gate_model_slugs only ever tested collision-FREE pairs, so deleting the
   detector below passed every assertion.

   Handled rather than wished away: buildIndex() REPORTS collisions,
   scripts/dumpModelSlugs.js refuses to write the snapshot when any exist,
   and the gate asserts zero in the real catalogue. Nothing silently serves
   one model's page at another's URL.

   ── THE SNAPSHOT IS THE STORE ──────────────────────────────────────────
   Best practice says store the slug, never recompute it from a display
   label, or renaming the label silently moves a live URL. There is no slug
   column to store it in: model pages are derived from DISTINCT
   products.model + products.brand, and `model_groups` only holds overrides
   for the models someone has curated.

   So the store is `src/config/modelSlugs.json`, generated by
   tools/dump_model_slugs.js and committed. The gate diffs this function's
   output against that file, so a model rename FAILS A GATE and appears in
   a reviewable diff instead of changing a URL in silence. No migration, no
   backfill, and the record is in version control where the decision is.

   ── NOT WIRED TO THE IMPORTERS, DELIBERATELY ───────────────────────────
   importJamesMartinFeed.js:80 and importHuntingtonBrass.js:171 each carry
   their own identical `slugify`, and the JMV one has been writing
   `collections.slug` for months. slugifyPart() below is NOT identical to
   them: it folds diacritics first, so "Café" gives `cafe` where theirs
   gives `caf`. Repointing the importers at this module could therefore
   change existing collections.slug values, which is a data migration, not
   a refactor. Left alone on purpose — see OPEN_ITEMS 11a.
   ═══════════════════════════════════════════════════════════════════════ */

/**
 * One path segment's worth of slug.
 *
 * NFD + combining-mark strip runs FIRST so an accented character becomes
 * its ASCII base rather than vanishing: "Café" -> "cafe", not "caf". The
 * importers' version drops it, which is the one intentional difference.
 */
function slugifyPart(s) {
  return String(s == null ? '' : s)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * The two slugs for one model-brand pair: { brand, model }, or null.
 * Pure: same inputs, same output, no clock, no DB, no I/O.
 *
 * Returns BOTH halves rather than a joined string, because the URL keeps
 * them in separate path segments. Nothing downstream should ever join them.
 *
 * @param {string} model  products.model
 * @param {string} brand  products.brand
 * @returns {{brand:string, model:string}|null}
 */
function modelSlug(model, brand) {
  const m = slugifyPart(model);
  const b = slugifyPart(brand);
  /* Both are required. An empty brand is a data defect — products.brand
     should always be set — and a one-segment fallback would make the URL
     shape depend on the data, so it is refused instead. The gate asserts
     the snapshot contains none. */
  if (!m || !b) return null;
  return { brand: b, model: m };
}

/**
 * Build the slug -> pair index used to resolve an inbound URL.
 *
 * Returns { index, collisions }. Collisions are RETURNED, not thrown: a
 * collision must fail a gate at build time, but must not take the
 * storefront down at request time. The caller decides.
 *
 * @param {Array<{model:string,brand:string}>} pairs
 */
/* The index key. "<brand>/<model>", which is exactly the path tail, so the
   lookup needs no reassembly and cannot disagree with the URL. */
function indexKey(brandSlug, modelSlug_) {
  return `${brandSlug}/${modelSlug_}`;
}

function buildIndex(pairs) {
  const index = new Map();
  const collisions = [];
  for (const p of (pairs || [])) {
    const sl = modelSlug(p.model, p.brand);
    if (!sl) continue;
    const slug = indexKey(sl.brand, sl.model);
    const prev = index.get(slug);
    if (prev) {
      collisions.push({ slug, a: prev, b: { model: p.model, brand: p.brand } });
      continue;                            // first one wins, deterministically
    }
    index.set(slug, { model: p.model, brand: p.brand });
  }
  return { index, collisions };
}

/**
 * Inbound "<brand>/<model>" -> the pair it names, or null.
 *
 * A lookup, never a parse. Case-folded and trimmed of surrounding slashes
 * so `/James-Martin-Vanities/Bristol/` resolves to the same page as the
 * canonical form — which is then what the caller should redirect to.
 */
function resolve(slug, index) {
  if (!slug || !index) return null;
  const key = String(slug).trim().replace(/^\/+|\/+$/g, '').toLowerCase();
  return index.get(key) || null;
}

/** The canonical path for a pair. One place, so no template builds it by hand. */
function modelPath(model, brand) {
  const sl = modelSlug(model, brand);
  return sl ? `/collections/vanity-models/${sl.brand}/${sl.model}` : null;
}

module.exports = { slugifyPart, modelSlug, indexKey, buildIndex, resolve, modelPath };
